######## 基本配置 ########

# Web 服务监听地址
listen: 0.0.0.0:8080


# HTTP 配置
insecure:
    # bind-address: ${IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS} # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
    # bind-port: ${IAM_AUTHZ_SERVER_INSECURE_BIND_PORT} # 提供非安全认证的监听端口，默认为 8080
    bind-address: 0.0.0.0
    bind-port: 8080

# HTTPS 配置
secure:
    bind-address: ${IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS} # HTTPS 安全模式的 IP 地址，默认为 0.0.0.0
    bind-port: ${IAM_AUTHZ_SERVER_SECURE_BIND_PORT} # 使用 HTTPS 安全模式的端口号，设置为 0 表示不启用 HTTPS，默认为 8443
    tls:
        #cert-dir: .iam/cert # TLS 证书所在的目录，默认值为 /var/run/iam
        #pair-name: iam # TLS 私钥对名称，默认 iam
        cert-key:
            cert-file: ${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE} # 包含 x509 证书的文件路径，用 HTTPS 认证
            private-key-file: ${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE} # TLS 私钥


######### 阿里灵积模型 ########

# API 申请：https://dashscope.aliyun.com/

# 是否启用阿里云灵积模型平台
enable-dashscopeai: true
dashscope-key: "sk-5dac8a2200cf43fbb92070e8419c2421"
#dashscope-keys: []


feature:
  enable-dashscopeai: true # 是否启用阿里云灵积模型平台

postgresql:
# 容器之间的请求不能用127.0.0.1，必须用mysql,redis代表容器的网络
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: root
  database: xuanxue
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10
  log-level: 1
  timzone: Asia%2FShanghai
    # charset: utf8
redis:
  host: redis     ## redis所在的服务器IP
  port: 6379
  ##密码，我这里没有设置，所以不填
  password:
  ## 设置最大连接数，0为无限
  pool:
    max-active: 8
    min-idle: 0
    max-idle: 8
    max-wait: -1